#ifndef STOCKBROKER_GLOBAL_H
#define STOCKBROKER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(STOCKBROKER_LIBRARY)
#  define STOCKBROKERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define STOCKBROKERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // STOCKBROKER_GLOBAL_H
